#!/usr/bin/python

# This is run by the BUILDER, never on the actual nodes.
# It will test to see if the domains exist, and only if they do not,
# Attempt to create and initialize.

import boto.sdb
from boto.sts import STSConnection
import sys
from pprint import pprint

appId ="{{ priam_cluster_name }}"

def put_record(domain, prop, val):
  print"Inserting into %s: %s -> %s" % (domain, prop, val)
  itemname ="%s.%s" % (appId, prop)
  sdb.put_attributes(domain, itemname, {"appId" : appId,"property" : prop,"value" : val})
  return

roleArn = '{{ priam_assume_role_arn|default('None') }}'

if roleArn == 'None':
    sdb = boto.sdb.connect_to_region("us-east-1")
else:
    sts = STSConnection()
    assumed = sts.assume_role(roleArn, 'sdb_script')
    sdb = boto.sdb.connect_to_region('us-east-1', aws_access_key_id=assumed.credentials.access_key, aws_secret_access_key=assumed.credentials.secret_key, security_token=assumed.credentials.session_token)

ii = sdb.lookup("InstanceIdentity", validate=True)
if ii is None:
  print"No InstanceIdentity, creating."
  ii = sdb.create_domain("InstanceIdentity")

pp = sdb.lookup("PriamProperties", validate=True)
if pp is None:
  print"No PriamProperties, creating."
  pp = sdb.create_domain("PriamProperties")

put_record("PriamProperties","priam.s3.bucket","{{ priam_s3_bucket }}")
put_record("PriamProperties","priam.s3.base_dir","{{ priam_s3_base_dir }}")
put_record("PriamProperties","priam.clustername","{{ priam_cluster_name }}")
put_record("PriamProperties","priam.data.location","{{ cassandra_data_location }}")
put_record("PriamProperties","priam.cache.location","{{ cassandra_cache_location }}")
put_record("PriamProperties","priam.commitlog.location","{{ cassandra_commitlog_location }}")
put_record("PriamProperties","priam.cass.home","{{ cassandra_home }}")
put_record("PriamProperties","priam.cass.startscript","{{ priam_cass_startscript }}")
put_record("PriamProperties","priam.cass.stopscript","{{ priam_cass_stopscript }}")
put_record("PriamProperties","priam.endpoint_snitch","{{ priam_endpoint_snitch }}")
put_record("PriamProperties","priam.upload.throttle","{{ priam_upload_throttle }}")
put_record("PriamProperties","priam.nativeTransport.enabled","{{ priam_native_transport_enabled }}")
put_record("PriamProperties","priam.internodeEncryption","{{ priam_internode_encryption }}")
{% if priam_multiregion_enable %}
put_record("PriamProperties","priam.multiregion.enable","{{ priam_multiregion_enable }}")
{% endif %}
{% if priam_zones_available !="" %}
put_record("PriamProperties","priam.zones.available","{{ priam_zones_available }}")
{% endif %}
{% if priam_acl_groupname !="" %}
put_record("PriamProperties","priam.acl.groupname","{{ priam_acl_groupname }}")
{% endif %}
{% if priam_vpc %}
put_record("PriamProperties","priam.vpc","{{ priam_vpc }}")
{% endif %}
put_record("PriamProperties","priam.backup.hour","{{ priam_backup_hour }}")
put_record("PriamProperties","priam.compaction.throughput","{{ priam_compaction_throughput }}")
# Not used in 2.1, but we'll set it for those on 2.0.x or less
put_record("PriamProperties","priam.memory.compaction.limit","{{ priam_compaction_limit }}")

# These are not tunable from Ansible, probably no reason to.
# Recommendations per http://docs.datastax.com/en/cassandra/2.1/cassandra/operations/ops_tune_jvm_c.html
# Direct memory is off-heap storage, ultimately setting XX:MaxDirectMemorySize
put_record("PriamProperties","priam.heap.size.t2.small","1024M")
put_record("PriamProperties","priam.heap.newgen.size.t2.small","100M")
put_record("PriamProperties","priam.direct.memory.size.t2.small","256M")
put_record("PriamProperties","priam.heap.size.t2.medium","1024M")
put_record("PriamProperties","priam.heap.newgen.size.t2.medium","200M")
put_record("PriamProperties","priam.direct.memory.size.t2.medium","206M")
put_record("PriamProperties","priam.heap.size.t2.large","2048M")
put_record("PriamProperties","priam.heap.newgen.size.t2.large","200M")
put_record("PriamProperties","priam.direct.memory.size.t2.large","974M")
put_record("PriamProperties","priam.heap.size.t2.xlarge","4096M")
put_record("PriamProperties","priam.heap.newgen.size.t2.xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.t2.xlarge","2460M")
put_record("PriamProperties","priam.heap.size.t2.2xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.t2.2xlarge","800M")
put_record("PriamProperties","priam.direct.memory.size.t2.2xlarge","5432M")
put_record("PriamProperties","priam.heap.size.m4.large","2048M")
put_record("PriamProperties","priam.heap.newgen.size.m4.large","200M")
put_record("PriamProperties","priam.direct.memory.size.m4.large","974M")
put_record("PriamProperties","priam.heap.size.m4.xlarge","4096M")
put_record("PriamProperties","priam.heap.newgen.size.m4.xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.m4.xlarge","2460M")
put_record("PriamProperties","priam.heap.size.m4.2xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.m4.2xlarge","800M")
put_record("PriamProperties","priam.direct.memory.size.m4.2xlarge","5432M")
put_record("PriamProperties","priam.heap.size.m4.4xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.m4.4xlarge","1600M")
put_record("PriamProperties","priam.direct.memory.size.m4.4xlarge","13424M")
put_record("PriamProperties","priam.heap.size.m4.10xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.m4.10xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.m4.10xlarge","37888M")
put_record("PriamProperties","priam.heap.size.m4.16xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.m4.16xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.m4.16xlarge","62464M")
put_record("PriamProperties","priam.heap.size.m3.medium","1024M")
put_record("PriamProperties","priam.heap.newgen.size.m3.medium","100M")
put_record("PriamProperties","priam.direct.memory.size.m3.medium","256M")
put_record("PriamProperties","priam.heap.size.m3.large","1920M")
put_record("PriamProperties","priam.heap.newgen.size.m3.large","200M")
put_record("PriamProperties","priam.direct.memory.size.m3.large","878M")
put_record("PriamProperties","priam.heap.size.m3.xlarge","3840M")
put_record("PriamProperties","priam.heap.newgen.size.m3.xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.m3.xlarge","2268M")
put_record("PriamProperties","priam.heap.size.m3.2xlarge","7680M")
put_record("PriamProperties","priam.heap.newgen.size.m3.2xlarge","800M")
put_record("PriamProperties","priam.direct.memory.size.m3.2xlarge","5048M")
put_record("PriamProperties","priam.heap.size.c5.large","1024M")
put_record("PriamProperties","priam.heap.newgen.size.c5.large","200M")
put_record("PriamProperties","priam.direct.memory.size.c5.large","206M")
put_record("PriamProperties","priam.heap.size.c5.xlarge","2048M")
put_record("PriamProperties","priam.heap.newgen.size.c5.xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.c5.xlarge","924M")
put_record("PriamProperties","priam.heap.size.c5.2xlarge","4096M")
put_record("PriamProperties","priam.heap.newgen.size.c5.2xlarge","800M")
put_record("PriamProperties","priam.direct.memory.size.c5.2xlarge","2360M")
put_record("PriamProperties","priam.heap.size.c5.4xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.c5.4xlarge","1600M")
put_record("PriamProperties","priam.direct.memory.size.c5.4xlarge","5232M")
put_record("PriamProperties","priam.heap.size.c5.8xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.c5.8xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.c5.8xlarge","15360M")
put_record("PriamProperties","priam.heap.size.c5.16xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.c5.16xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.c5.16xlarge","33792M")
put_record("PriamProperties","priam.heap.size.c4.large","1024M")
put_record("PriamProperties","priam.heap.newgen.size.c4.large","200M")
put_record("PriamProperties","priam.direct.memory.size.c4.large","256M")
put_record("PriamProperties","priam.heap.size.c4.xlarge","1920M")
put_record("PriamProperties","priam.heap.newgen.size.c4.xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.c4.xlarge","828M")
put_record("PriamProperties","priam.heap.size.c4.2xlarge","3840M")
put_record("PriamProperties","priam.heap.newgen.size.c4.2xlarge","800M")
put_record("PriamProperties","priam.direct.memory.size.c4.2xlarge","2168M")
put_record("PriamProperties","priam.heap.size.c4.4xlarge","7680M")
put_record("PriamProperties","priam.heap.newgen.size.c4.4xlarge","1600M")
put_record("PriamProperties","priam.direct.memory.size.c4.4xlarge","4848M")
put_record("PriamProperties","priam.heap.size.c4.8xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.c4.8xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.c4.8xlarge","12288M")
put_record("PriamProperties","priam.heap.size.c3.large","1024M")
put_record("PriamProperties","priam.heap.newgen.size.c3.large","200M")
put_record("PriamProperties","priam.direct.memory.size.c3.large","256M")
put_record("PriamProperties","priam.heap.size.c3.xlarge","1920M")
put_record("PriamProperties","priam.heap.newgen.size.c3.xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.c3.xlarge","828M")
put_record("PriamProperties","priam.heap.size.c3.2xlarge","3840M")
put_record("PriamProperties","priam.heap.newgen.size.c3.2xlarge","800M")
put_record("PriamProperties","priam.direct.memory.size.c3.2xlarge","2168M")
put_record("PriamProperties","priam.heap.size.c3.4xlarge","7680M")
put_record("PriamProperties","priam.heap.newgen.size.c3.4xlarge","1600M")
put_record("PriamProperties","priam.direct.memory.size.c3.4xlarge","4848M")
put_record("PriamProperties","priam.heap.size.c3.8xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.c3.8xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.c3.8xlarge","12288M")
put_record("PriamProperties","priam.heap.size.x1.16xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.x1.16xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.x1.16xlarge","246784M")
put_record("PriamProperties","priam.heap.size.x1.32xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.x1.32xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.x1.32xlarge","496640M")
put_record("PriamProperties","priam.heap.size.r3.large","3904M")
put_record("PriamProperties","priam.heap.newgen.size.r3.large","200M")
put_record("PriamProperties","priam.direct.memory.size.r3.large","2366M")
put_record("PriamProperties","priam.heap.size.r3.xlarge","7808M")
put_record("PriamProperties","priam.heap.newgen.size.r3.xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.r3.xlarge","5244M")
put_record("PriamProperties","priam.heap.size.r3.2xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.r3.2xlarge","800M")
put_record("PriamProperties","priam.direct.memory.size.r3.2xlarge","12856M")
put_record("PriamProperties","priam.heap.size.r3.4xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.r3.4xlarge","1600M")
put_record("PriamProperties","priam.direct.memory.size.r3.4xlarge","28272M")
put_record("PriamProperties","priam.heap.size.r3.8xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.r3.8xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.r3.8xlarge","59392M")
put_record("PriamProperties","priam.heap.size.r4.large","3904M")
put_record("PriamProperties","priam.heap.newgen.size.r4.large","200M")
put_record("PriamProperties","priam.direct.memory.size.r4.large","2366M")
put_record("PriamProperties","priam.heap.size.r4.xlarge","7808M")
put_record("PriamProperties","priam.heap.newgen.size.r4.xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.r4.xlarge","5244M")
put_record("PriamProperties","priam.heap.size.r4.2xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.r4.2xlarge","800M")
put_record("PriamProperties","priam.direct.memory.size.r4.2xlarge","12856M")
put_record("PriamProperties","priam.heap.size.r4.4xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.r4.4xlarge","1600M")
put_record("PriamProperties","priam.direct.memory.size.r4.4xlarge","28272M")
put_record("PriamProperties","priam.heap.size.r4.8xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.r4.8xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.r4.8xlarge","59392M")
put_record("PriamProperties","priam.heap.size.r4.16xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.r4.16xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.r4.16xlarge","121856M")
put_record("PriamProperties","priam.heap.size.i3.large","3904M")
put_record("PriamProperties","priam.heap.newgen.size.i3.large","200M")
put_record("PriamProperties","priam.direct.memory.size.i3.large","2366M")
put_record("PriamProperties","priam.heap.size.i3.xlarge","7808M")
put_record("PriamProperties","priam.heap.newgen.size.i3.xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.i3.xlarge","5244M")
put_record("PriamProperties","priam.heap.size.i3.2xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.i3.2xlarge","800M")
put_record("PriamProperties","priam.direct.memory.size.i3.2xlarge","12856M")
put_record("PriamProperties","priam.heap.size.i3.4xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.i3.4xlarge","1600M")
put_record("PriamProperties","priam.direct.memory.size.i3.4xlarge","28272M")
put_record("PriamProperties","priam.heap.size.i3.8xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.i3.8xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.i3.8xlarge","59392M")
put_record("PriamProperties","priam.heap.size.i3.16xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.i3.16xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.i3.16xlarge","121856M")
put_record("PriamProperties","priam.heap.size.i2.xlarge","7808M")
put_record("PriamProperties","priam.heap.newgen.size.i2.xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.i2.xlarge","5244M")
put_record("PriamProperties","priam.heap.size.i2.2xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.i2.2xlarge","800M")
put_record("PriamProperties","priam.direct.memory.size.i2.2xlarge","12856M")
put_record("PriamProperties","priam.heap.size.i2.4xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.i2.4xlarge","1600M")
put_record("PriamProperties","priam.direct.memory.size.i2.4xlarge","28272M")
put_record("PriamProperties","priam.heap.size.i2.8xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.i2.8xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.i2.8xlarge","59392M")
put_record("PriamProperties","priam.heap.size.d2.xlarge","7808M")
put_record("PriamProperties","priam.heap.newgen.size.d2.xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.d2.xlarge","5244M")
put_record("PriamProperties","priam.heap.size.d2.2xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.d2.2xlarge","800M")
put_record("PriamProperties","priam.direct.memory.size.d2.2xlarge","12856M")
put_record("PriamProperties","priam.heap.size.d2.4xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.d2.4xlarge","1600M")
put_record("PriamProperties","priam.direct.memory.size.d2.4xlarge","28272M")
put_record("PriamProperties","priam.heap.size.d2.8xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.d2.8xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.d2.8xlarge","59392M")
put_record("PriamProperties","priam.heap.size.m1.small","870M")
put_record("PriamProperties","priam.heap.newgen.size.m1.small","50M")
put_record("PriamProperties","priam.direct.memory.size.m1.small","218M")
put_record("PriamProperties","priam.heap.size.m1.medium","1024M")
put_record("PriamProperties","priam.heap.newgen.size.m1.medium","100M")
put_record("PriamProperties","priam.direct.memory.size.m1.medium","256M")
put_record("PriamProperties","priam.heap.size.m1.large","1920M")
put_record("PriamProperties","priam.heap.newgen.size.m1.large","200M")
put_record("PriamProperties","priam.direct.memory.size.m1.large","878M")
put_record("PriamProperties","priam.heap.size.m1.xlarge","3840M")
put_record("PriamProperties","priam.heap.newgen.size.m1.xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.m1.xlarge","2268M")
put_record("PriamProperties","priam.heap.size.c1.medium","870M")
put_record("PriamProperties","priam.heap.newgen.size.c1.medium","200M")
put_record("PriamProperties","priam.direct.memory.size.c1.medium","218M")
put_record("PriamProperties","priam.heap.size.c1.xlarge","1792M")
put_record("PriamProperties","priam.heap.newgen.size.c1.xlarge","448M")
put_record("PriamProperties","priam.direct.memory.size.c1.xlarge","720M")
put_record("PriamProperties","priam.heap.size.cc2.8xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.cc2.8xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.cc2.8xlarge","12416M")
put_record("PriamProperties","priam.heap.size.cg1.4xlarge","5760M")
put_record("PriamProperties","priam.heap.newgen.size.cg1.4xlarge","1440M")
put_record("PriamProperties","priam.direct.memory.size.cg1.4xlarge","3448M")
put_record("PriamProperties","priam.heap.size.m2.xlarge","4378M")
put_record("PriamProperties","priam.heap.newgen.size.m2.xlarge","200M")
put_record("PriamProperties","priam.direct.memory.size.m2.xlarge","2721M")
put_record("PriamProperties","priam.heap.size.m2.2xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.m2.2xlarge","400M")
put_record("PriamProperties","priam.direct.memory.size.m2.2xlarge","6095M")
put_record("PriamProperties","priam.heap.size.m2.4xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.m2.4xlarge","800M")
put_record("PriamProperties","priam.direct.memory.size.m2.4xlarge","14750M")
put_record("PriamProperties","priam.heap.size.cr1.8xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.cr1.8xlarge","2048M")
put_record("PriamProperties","priam.direct.memory.size.cr1.8xlarge","59392M")
put_record("PriamProperties","priam.heap.size.hi1.4xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.hi1.4xlarge","1600M")
put_record("PriamProperties","priam.direct.memory.size.hi1.4xlarge","12528M")
put_record("PriamProperties","priam.heap.size.hs1.8xlarge","8192M")
put_record("PriamProperties","priam.heap.newgen.size.hs1.8xlarge","1600M")
put_record("PriamProperties","priam.direct.memory.size.hs1.8xlarge","26992M")
