#!/bin/dash
#
# ephemeral-setup
#
# chkconfig S 02 98
#
### BEGIN INIT INFO
# Provides: ephemeral-mkdirs
# X-Start-Before: mdadm postfix
# X-Start-After: ephemeral-raid
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Required-Start: ephemeral-raid
# Required-Stop:
# Short-Description: Tool to automatically setup ephemeral disks
# Description: A tool that sets up ephemeral disks on EC2
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions
. /lib/init/vars.sh

service="Ephemeral directory setup service"

create_dir()
{
  echo $1
  OLDIFS=$IFS
  IFS=","
  set -- $1
  IFS=$OLDIFS
  echo "### $1"
  mkdir -p $1
  chown $2:$3 $1
  chmod $4 $1
}

case "$1" in
  start)

	MKDIRLIST="/etc/ephemeral-dirs"
	if [ ! -e ${MKDIRLIST} ]; then
	  echo "No ephemeral directories defined, skipping"
	  exit 0
	fi
	while read line
	do
	  create_dir $line
	done < ${MKDIRLIST}

        exit 0
        ;;
  stop)
        exit 0
        ;;
  *)
        echo "Usage: /etc/init.d/$NAME start" >&2
        exit 1
        ;;
esac

exit 0

