---
- name: Copy jetty app context xml file
  copy: src=fluxdemo_middle.xml dest={{ fluxdemo_middle_webapps_root }}/root.xml owner={{ jetty_user }} group={{ jetty_group }} mode=0644
  notify: restart fluxdemo middle
  when: servlet_container == "jetty9"

- include: acquire_build.yml

- name: Remove any old version
  file: path={{ fluxdemo_middle_webapps_root }}/root state=absent
  
- name: Create fluxdemo_middle deployment directory
  file: path={{ fluxdemo_middle_webapps_root }}/root state=directory

- name: Decompress fluxdemo_middle WAR file
  command: chdir={{ fluxdemo_middle_webapps_root }}/root jar xf /tmp/fluxdemo_middle.war
  notify: restart fluxdemo middle
  
- name: Remove source WAR file
  file: path=/tmp/fluxdemo_middle.war state=absent
  notify: restart fluxdemo middle

- name: Copy middletier.properties
  template: src=middletier.properties dest={{ fluxdemo_middle_webapps_root }}/root/WEB-INF/classes/middletier.properties owner={{ servlet_container_user }} group={{ servlet_container_group }} mode=0644

- name: Copy log4j.properties
  template: src=log4j.properties dest={{ fluxdemo_middle_webapps_root }}/root/WEB-INF/classes/log4j.properties owner={{ servlet_container_user }} group={{ servlet_container_group }} mode=0644

